### ISSUE TITLE
execSync dependency does not work in node v0.12

### ISSUE THREAD

**Issue by esbena** [wala/jsdelta#5]
```
$ node --version
v0.12.2
$ node delta.js 
module.js:338
    throw err;
          ^
Error: Cannot find module './build/Release/shell'
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (...jsdelta/node_modules/execSync/index.js:30:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by esbena** [comment]
97cf1557a533e959d49abef3b4e41619f2cdf142 has some code that works for node v0.12 using child_process.execSync...
